set_property PACKAGE_PIN E3 [get_ports clk_in]
set_property PACKAGE_PIN N17 [get_ports key_ok]
set_property PACKAGE_PIN P18 [get_ports key_select_down]
set_property PACKAGE_PIN B11 [get_ports vga_h_sync]
set_property PACKAGE_PIN B12 [get_ports vga_v_sync]
set_property PACKAGE_PIN A3 [get_ports {vga_r[0]}]
set_property PACKAGE_PIN B4 [get_ports {vga_r[1]}]
set_property PACKAGE_PIN C5 [get_ports {vga_r[2]}]
set_property PACKAGE_PIN A4 [get_ports {vga_r[3]}]
set_property PACKAGE_PIN C6 [get_ports {vga_g[0]}]
set_property PACKAGE_PIN A5 [get_ports {vga_g[1]}]
set_property PACKAGE_PIN B6 [get_ports {vga_g[2]}]
set_property PACKAGE_PIN A6 [get_ports {vga_g[3]}]
set_property PACKAGE_PIN B7 [get_ports {vga_b[0]}]
set_property PACKAGE_PIN C7 [get_ports {vga_b[1]}]
set_property PACKAGE_PIN D7 [get_ports {vga_b[2]}]
set_property PACKAGE_PIN D8 [get_ports {vga_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in]
set_property IOSTANDARD LVCMOS33 [get_ports key_ok]
set_property IOSTANDARD LVCMOS33 [get_ports key_select_down]
set_property IOSTANDARD LVCMOS33 [get_ports vga_h_sync]
set_property IOSTANDARD LVCMOS33 [get_ports vga_v_sync]

set_property PACKAGE_PIN C12 [get_ports rstn_pb]
set_property IOSTANDARD LVCMOS33 [get_ports rstn_pb]

set_property PACKAGE_PIN J15 [get_ports {mode_game[0]}]
set_property PACKAGE_PIN L16 [get_ports {mode_game[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode_game[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode_game[0]}]



set_property PACKAGE_PIN J17 [get_ports {enable_7seg[0]}]
set_property PACKAGE_PIN J18 [get_ports {enable_7seg[1]}]
set_property PACKAGE_PIN T9 [get_ports {enable_7seg[2]}]
set_property PACKAGE_PIN J14 [get_ports {enable_7seg[3]}]
set_property PACKAGE_PIN P14 [get_ports {enable_7seg[4]}]
set_property PACKAGE_PIN T14 [get_ports {enable_7seg[5]}]
set_property PACKAGE_PIN K2 [get_ports {enable_7seg[6]}]
set_property PACKAGE_PIN U13 [get_ports {enable_7seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enable_7seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enable_7seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enable_7seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enable_7seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enable_7seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enable_7seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enable_7seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enable_7seg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports ca_o]
set_property IOSTANDARD LVCMOS33 [get_ports cb_o]
set_property IOSTANDARD LVCMOS33 [get_ports cc_o]
set_property IOSTANDARD LVCMOS33 [get_ports cd_o]
set_property IOSTANDARD LVCMOS33 [get_ports ce_o]
set_property IOSTANDARD LVCMOS33 [get_ports cf_o]
set_property IOSTANDARD LVCMOS33 [get_ports cg_o]
set_property IOSTANDARD LVCMOS33 [get_ports dp_o]
set_property PACKAGE_PIN H15 [get_ports dp_o]
set_property PACKAGE_PIN T10 [get_ports ca_o]
set_property PACKAGE_PIN R10 [get_ports cb_o]
set_property PACKAGE_PIN K16 [get_ports cc_o]
set_property PACKAGE_PIN K13 [get_ports cd_o]
set_property PACKAGE_PIN P15 [get_ports ce_o]
set_property PACKAGE_PIN T11 [get_ports cf_o]
set_property PACKAGE_PIN L18 [get_ports cg_o]




set_property PACKAGE_PIN M18 [get_ports key_select_up]
set_property IOSTANDARD LVCMOS33 [get_ports key_select_up]


connect_debug_port u_ila_0/probe9 [get_nets [list {game_inst/cur_value_frame_buffer[0]} {game_inst/cur_value_frame_buffer[1]} {game_inst/cur_value_frame_buffer[2]} {game_inst/cur_value_frame_buffer[3]} {game_inst/cur_value_frame_buffer[4]} {game_inst/cur_value_frame_buffer[5]} {game_inst/cur_value_frame_buffer[6]} {game_inst/cur_value_frame_buffer[7]} {game_inst/cur_value_frame_buffer[8]} {game_inst/cur_value_frame_buffer[9]} {game_inst/cur_value_frame_buffer[10]} {game_inst/cur_value_frame_buffer[11]}]]



